remote_theme: pages-themes/hacker@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one

title: Notes
description: markdown notes
show_downloads: false
show_github_link: false

markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false
  syntax_highlighter: rouge
  emoji: true
  mermaid:
    theme: default
    flowchart:
      curve: linear